# Site settings
title: Parker Hance
description: Software Engineer | AI Enthusiast | Student
baseurl: "/blog" # GitHub Pages repository name
url: "https://cocofruit.github.io" # Your GitHub Pages URL

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
